name: CI

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - '**'
    - '!docs/**'
    tags:
    - 'v*'
  pull_request:
    paths:
    - '**'
    - '!docs/**'

env:
  LC_ALL: en_US.UTF-8
  PUBLISH: ${{ (github.repository == 'kdex-tech/backend-static') && startsWith(github.ref, 'refs/tags/') && (github.event_name != 'pull_request') }}

defaults:
  run:
    shell: bash

permissions:
  packages: write
  contents: read

jobs:
  ci:
    name: Build, Test, Publish
    runs-on: ubuntu-latest
    steps:
    - name: Clone the code
      uses: actions/checkout@v6

    - name: Set Caddy Version
      id: caddy_version
      run: |
        CADDY_VERSION=$(grep -oP 'caddy:\K[0-9.]+' Dockerfile)
        echo "CADDY_VERSION=${CADDY_VERSION}" >> $GITHUB_ENV
        echo "Found Caddy version: ${CADDY_VERSION}"

    - name: Install Caddy
      run: |
        sudo apt update
        sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
        sudo apt update
        sudo apt install caddy=${{ env.CADDY_VERSION }}

    - name: Run Unit Tests
      run: make test

    - name: Publish Docker Image
      if: ${{ env.PUBLISH == 'true' }}
      uses: ./.github/actions/publish-docker-image
